language: r
sudo: false
cache: packages

script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check --as-cran countprop*tar.gz

after_script:
  - tar -ztvf countprop_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat countprop.Rcheck/00*